/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create_game` | `/create_game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sports/badminton`; params?: Router.UnknownInputParams; } | { pathname: `/sports/basketball`; params?: Router.UnknownInputParams; } | { pathname: `/sports/cricket`; params?: Router.UnknownInputParams; } | { pathname: `/sports/football`; params?: Router.UnknownInputParams; } | { pathname: `/sports/volleyball`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create_game` | `/create_game`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/sports/badminton`; params?: Router.UnknownOutputParams; } | { pathname: `/sports/basketball`; params?: Router.UnknownOutputParams; } | { pathname: `/sports/cricket`; params?: Router.UnknownOutputParams; } | { pathname: `/sports/football`; params?: Router.UnknownOutputParams; } | { pathname: `/sports/volleyball`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create_game${`?${string}` | `#${string}` | ''}` | `/create_game${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/games${`?${string}` | `#${string}` | ''}` | `/games${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/venues${`?${string}` | `#${string}` | ''}` | `/venues${`?${string}` | `#${string}` | ''}` | `/auth/create-account${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/sports/badminton${`?${string}` | `#${string}` | ''}` | `/sports/basketball${`?${string}` | `#${string}` | ''}` | `/sports/cricket${`?${string}` | `#${string}` | ''}` | `/sports/football${`?${string}` | `#${string}` | ''}` | `/sports/volleyball${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create_game` | `/create_game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sports/badminton`; params?: Router.UnknownInputParams; } | { pathname: `/sports/basketball`; params?: Router.UnknownInputParams; } | { pathname: `/sports/cricket`; params?: Router.UnknownInputParams; } | { pathname: `/sports/football`; params?: Router.UnknownInputParams; } | { pathname: `/sports/volleyball`; params?: Router.UnknownInputParams; };
    }
  }
}
